Updated composer installation instructions
talyssonoc/react-laravel pull request #73
Opened 2016-10-01 12:47 UTC by janhohner

It is now recommended to use the command line to add new dependencies to a project.

2016-10-05 12:24 UTC, talyssonoc commented
Nice!

2016-10-05 12:25 UTC, talyssonoc requested changes

2016-10-05 12:25 UTC, talyssonoc commented on README.md
> +  composer require talyssonoc/react-laravel:0.11
Can you put the `$` back on? This pattern is used on the rest of the README.

2016-10-06 15:25 UTC, janhohner commented on README.md
> +  composer require talyssonoc/react-laravel:0.11
Ok 👍  I just added it back.

2016-10-06 15:43 UTC, talyssonoc approved these changes

2016-10-06 15:43 UTC, merged